RBAC/urls.py
#coding:utf-8
'''
Created on 2018年5月10日

@author: yuguanc
'''

from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('view/', views.login, name='login'),
    path('view/regist/<str:argu>/', views.regist, name='regist'),
    path('view/resetpsd/<str:argu>/', views.resetpasswd, name='resetpsds'),
    path('user/', views.dashboard, name='dashboard'),
    path('user/main/', views.main, name='main'),
    path('user/logout/', views.logout, name='logout'),
    path('user/changepsd/', views.changepsd, name='changepsd'),
    path('user/info/', views.userinfo, name='userinfo'),
    path('user/changeinfo/', views.changeuserinfo, name='changeuserinfo'),
    
    path('manage/user/', views.userlist, name='userview'),
    path('manage/user/list/', views.userlisttable, name='userlist'),
    path('manage/user/add/', views.user_add, name='useradd'),
    path('manage/user/disactivate/', views.user_disactivate, name='userdisactivate'),
    
    path('manage/userrequest/', views.userregistlist, name='userregistview'),
    path('manage/userrequest/list/', views.userregisttable, name='userregistlist'),
    path('manage/userrequest/action/', views.userregistaction, name='userregistaction'),
    path('manage/userrequest/stop/', views.user_request_cancle, name='userregiststop'),
    
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SeMF/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('semf/', admin.site.urls),
    path('',include('RBAC.urls')),
    path('notice/',include('NoticeManage.urls')),
    path('asset/',include('AssetManage.urls')),
    path('vuln/',include('VulnManage.urls')),
    path('chart/',include('ChartManage.urls')),
    path('article/',include('ArticleManage.urls')),
    path('mapped/',include('MappedManage.urls')),
    path('task/',include('TaskManage.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    
#handler404 = views.page_not_found
#handler500 = views.page_error
#handler403 = views.permission_denied

RBAC/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import django.utils.timezone as timezone

# Create your models here.

class Area(models.Model):
    name = models.CharField('属地信息',max_length = 90,unique=True)
    parent = models.ForeignKey('self',verbose_name='父级属地',related_name='assetarea_area',null=True,blank=True,on_delete=models.CASCADE)
    def __str__(self):
        #显示层级菜单
        title_list = [self.name]
        p = self.parent
        while p:
            title_list.insert(0,p.name)
            p = p.parent
        return '-'.join(title_list)

#设置菜单
class Menu(models.Model):
    title = models.CharField(u'菜单标题',max_length = 25,unique=True)
    icon = models.CharField(u'菜单图标',max_length = 50)
    parent = models.ForeignKey('self',verbose_name=u'父菜单',related_name='menu_menu',null=True,blank=True,on_delete=models.CASCADE)
    
    def __str__(self):
        #显示层级菜单
        title_list = [self.title]
        p = self.parent
        while p:
            title_list.insert(0,p.title)
            p = p.parent
        return '-'.join(title_list)

#设置访问链接
class Permission(models.Model):
    title = models.CharField(u'权限标题',max_length = 50,unique=True)
    is_menu = models.BooleanField('菜单显示',default=False)
    url = models.CharField(max_length=128)
    menu = models.ForeignKey(Menu, null=True,verbose_name=u'权限菜单',related_name='permission_menu',on_delete=models.CASCADE)
    
    def __str__(self):
        return '{menu}--{permission}'.format(menu=self.menu,permission=self.title)
    
#设置角色和权限
class Role(models.Model):
    title = models.CharField(u'角色名称',max_length=25,unique=True)
    permissions = models.ManyToManyField(Permission,verbose_name=u'权限菜单',related_name='role_permission')
    
    def __str__(self):
        return self.title

REQUEST_STATUS=(
    ('0','待审批'),
    ('1','审批通过'),
    ('2','审批拒绝'),
    )

#注册有审批时使用
class UserRequest(models.Model):
    email = models.EmailField('申请邮箱')
    urlarg = models.CharField('注册参数',max_length=50)
    status = models.CharField('审批状态',max_length=50,default='0',choices=REQUEST_STATUS)
    is_check = models.BooleanField('是否审批',default=False)
    is_use = models.BooleanField('是否使用',default=False)
    request_type = models.ForeignKey(Role,verbose_name=u'账号权限',related_name='userrequest_role',on_delete=models.CASCADE)
    starttime = models.DateTimeField('申请时间',auto_now_add=True)
    updatetime = models.DateTimeField('审批时间',auto_now=True)
    
    area =  models.ForeignKey(Area,verbose_name='所属区域',related_name='userrequest_area',null=True,on_delete=models.CASCADE,limit_choices_to={'parent__isnull':True})
    action_user = models.ForeignKey(User,related_name='regist_for_actionuser',on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.email
    
    
#重置密码时使用
class UserResetpsd(models.Model):
    email = models.EmailField('申请邮箱')
    urlarg = models.CharField('重置参数',max_length=50)
    is_check = models.BooleanField('是否使用',default=False)
    updatetime = models.DateField('更新时间',auto_now=True)
    def __str__(self):
        return self.email




#用户附加属性
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    user_num =  models.CharField(u'员工编号',max_length=50,null=True,blank=True)
    title =  models.CharField(u'职位名称',max_length=50)
    
    telephone = models.CharField(u'座机号码',max_length=50,null=True,blank=True)
    mobilephone = models.CharField(u'手机号码',max_length=50)
    description = models.TextField(u'用户简介')
    error_count = models.IntegerField(u'错误登陆',default=0)
    lock_time = models.DateTimeField(u'锁定时间',default = timezone.now)
    
    parent_email = models.EmailField('上级邮箱',null=True,blank=True)
    parent = models.ForeignKey(User,verbose_name='上级汇报',related_name='user_parent',null=True,blank=True,on_delete=models.CASCADE)
    area =  models.ForeignKey(Area,verbose_name='所属区域',related_name='user_area',null=True,on_delete=models.CASCADE,limit_choices_to={'parent__isnull':True})
    
    roles = models.ManyToManyField(Role,verbose_name=u'所属角色',related_name='user_role')
    
    def __str__(self):
        return self.user.username

#同步保存信息  
@receiver(post_save, sender=User) 
def create_user_profile(sender, instance, created, **kwargs):  
    if created:  
        Profile.objects.get_or_create(user=instance)  

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

RBAC/views.py
#coding:utf-8
from django.shortcuts import render,HttpResponseRedirect,get_object_or_404

# Create your views here.
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import django.utils.timezone as timezone
from django.contrib import auth
import datetime,json
from SeMFSetting.Functions.checkpsd import checkpsd
from . import forms,models
import hashlib 
from django.contrib.auth.hashers import make_password 
from SeMFSetting.views import paging,strtopsd
from SeMFSetting.Functions import mails
from ArticleManage.models import Article
from AssetManage.models import Asset
from VulnManage.models import Vulnerability,Vulnerability_scan
from .service.init_permission import init_permission
from django.utils.html import escape


REAUEST_STATUS={
    '0':'待审批',
    '1':'审批通过',
    '2':'审批拒绝',
    }

@login_required
def main(request):
    article = Article.objects.filter(article_status='1').last()
    article_list =  Article.objects.filter(article_status='1').order_by('-article_updatetime')[:15]
    
    user_count = User.objects.all().count()
    article_count = Article.objects.filter(article_status='1').count()
    asset_count = Asset.objects.all().count()
    cnvdvuln_count = Vulnerability.objects.all().count()
    vuln_count = Vulnerability_scan.objects.all().count()
    vuln_fix_count = Vulnerability_scan.objects.exclude(fix_status__in=[0,1]).count()
    
    return render(request,'RBAC/main.html',{
        'article':article,
        'article_list':article_list,
        'user_count':user_count,
        'article_count':article_count,
        'asset_count':asset_count,
        'cnvdvuln_count':cnvdvuln_count,
        'vuln_count':vuln_count,
        'vuln_fix_count':vuln_fix_count
        })

@login_required
def dashboard(request):
    return render(request,'Dashboard.html')


@csrf_protect
def regist(request,argu):
    error = ''
    if argu == 'regist':
        if request.method == 'POST':
            form = forms.UserRequestForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                user_get = User.objects.filter(username=email)
                if user_get:
                    error = '用户已存在'
                else:
                    userregist_get = models.UserRequest.objects.filter(email = email)
                    if userregist_get.count()>2:
                        error = '用户已多次添加'
                    else:
                        area = form.cleaned_data['area']
                        request_type = form.cleaned_data['request_type']
                        urlarg = strtopsd(email)
                        models.UserRequest.objects.get_or_create(
                            email=email,
                            urlarg=urlarg,
                            area=area,
                            request_type=request_type,
                            )
                        #res = mails.sendregistmail(email, urlarg)
                        error = '申请成功，审批通过后会向您发送邮箱'
            else:
                error ='请检查输入'
        else:
            form = forms.UserRequestForm()
        return render(request,'RBAC/registrequest.html',{'form':form,'error':error})
    else:
        regist_get = get_object_or_404(models.UserRequest,urlarg=argu,is_use=False)
        if request.method == 'POST':
            form = forms.Account_Reset_Form(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                firstname = form.cleaned_data['firstname']
                lastname = form.cleaned_data['lastname']
                password = form.cleaned_data['password']
                repassword = form.cleaned_data['repassword']
                username = email.split("@")[0]
                check_res = checkpsd(password)
                if check_res:
                    if regist_get.email == email:
                        if password == repassword:
                            user_create = auth.authenticate(username = username,password = password)
                            if user_create:
                                error = '用户已存在'
                            else:
                                user_create = User.objects.create_user(
                                    first_name = firstname,
                                    last_name = lastname,
                                    username=username,
                                    password=password,
                                    email=email,
                                   )
                                user_create.profile.roles.add(regist_get.request_type)
                                user_create.profile.area=regist_get.area
                                user_create.save()
                                regist_get.is_use=True
                                regist_get.save()
                                return HttpResponseRedirect('/view/')
                        else:
                            error = '两次密码不一致'
                    else:
                        error = '密码必须6位以上且包含字母、数字'
                else:
                    error = '恶意注册是不对滴'
            else:
                error = '请检查输入'
        else:
            form = forms.Account_Reset_Form()
        return render(request,'RBAC/regist.html',{'form':form,'error':error})

@csrf_protect
def resetpasswd(request,argu = 'resetpsd'):
    error = ''
    if argu =='resetpsd':
        if request.method == 'POST':
            form = forms.ResetpsdRequestForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                user = get_object_or_404(User,email=email)
                if user:
                    hash_res = hashlib.md5()
                    hash_res.update(make_password(email).encode('utf-8'))
                    urlarg = hash_res.hexdigest()
                    models.UserResetpsd.objects.get_or_create(
                        email=email,
                        urlarg=urlarg
                        )
                    res = mails.sendresetpsdmail(email,urlarg)
                    if res:
                        error = '申请已发送，请检查邮件通知，请注意检查邮箱'
                    else:
                        error = '重置邮件发送失败，请重试'
                else:
                    error ='请检查信息是否正确'
            else:
                error ='请检查输入'
        else:
            form = forms.ResetpsdRequestForm()
        return render(request,'RBAC/resetpsdquest.html',{'form':form,'error':error})
    else:
        resetpsd = get_object_or_404(models.UserResetpsd,urlarg=argu)
        if resetpsd:
            email_get = resetpsd.email
            if request.method == 'POST':
                form = forms.ResetpsdForm(request.POST)
                if form.is_valid():
                    email = form.cleaned_data['email']
                    password = form.cleaned_data['password']
                    repassword = form.cleaned_data['repassword']
                    if checkpsd(password):
                        if password==repassword:
                            if email_get==email:
                                user = get_object_or_404(User,email=email)
                                if user:
                                    user.set_password(password)
                                    user.save()
                                    resetpsd.delete()
                                    return HttpResponseRedirect('/view/')
                                    
                                else:
                                    error = '用户信息有误'
                            else:
                                error = '用户邮箱不匹配'
                        else:
                            error = '两次密码不一致'
                    else:
                        error = '密码必须6位以上且包含字母、数字'
                else:
                    error = '请检查输入'
            else:
                form = forms.ResetpsdForm()
            return render(request,'RBAC/resetpsd.html',{'form':form,'error':error,'title':'重置'})
                        
                        

@login_required
@csrf_protect
def changeuserinfo(request):
    user = request.user
    error = ''
    if request.method == 'POST':
        form = forms.UserInfoForm(request.POST,instance=user.profile)
        if form.is_valid():
            if 'parent_email' in form.changed_data:
                parent_email = form.cleaned_data['parent_email']
                parent_user = User.objects.filter(email =parent_email ).first()
                if parent_user:
                    user.profile.parent = parent_user
                    user.save()
            form.save()
            error= '修改成功'
        else:
            error = '请检查输入'
        return render(request,'formedit.html',{'form':form,'post_url':'changeuserinfo','error':error})
    else:
        form = forms.UserInfoForm(instance=user.profile)
    return render(request,'formedit.html',{'form':form,'post_url':'changeuserinfo'})



@login_required
def userinfo(request):
    return render(request,'RBAC/userinfo.html')


@login_required
@csrf_protect
def changepsd(request):
    error =''
    if request.method == 'POST':
        form = forms.ChangPasswdForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            re_new_password = form.cleaned_data['re_new_password']
            username = request.user.username 
            if checkpsd(new_password):
                if new_password and new_password == re_new_password:
                    if old_password:
                        user = auth.authenticate(username = username,password = old_password)
                        if user:
                            user.set_password(new_password)
                            user.save()

templates/RBAC/regist.html
{% extends "RBAC/login.html" %} 
<meta charset="UTF-8">

{% block user %}
	<form method="post" class="layui-form layui-form-pane" >
	  	{% csrf_token %}
	  	{{ form.firstname}}
	  	<hr class="hr15">
	  	{{ form.lastname}}
	  	<hr class="hr15">
	  	{{ form.email}}
	  	<hr class="hr15">
	  	{{ form.password}}
	  	<hr class="hr15">
	  	{{ form.repassword}}
	  	<hr class="hr15">
		<input value="注册" style="width:100%;" type="submit">
		<hr class="hr20" >
     	<div class="layui-row">
     		<div class="layui-col-xs6">
      			<span><a href="{% url 'login' %}">已有账号？返回登录</a></span>
      		</div>
		    <div class="layui-col-xs6" align='right'>
				<span><a href="#">忘记密码？密码重置</a></span>
			</div>
		</div>
 	</form>
{% endblock %}

templates/RBAC/registrequest.html
{% extends "RBAC/login.html" %} 
<meta charset="UTF-8">

{% block user %}
	<div class="x-body layui-anim layui-anim-up">
	<form method="post" class="layui-form" >
		<div class="layui-form-item">
		  	<div class="layui-form-item">
				{% csrf_token %}
				{{ form.as_table }}
			</div>
			<input value="申请" style="width:100%;" type="submit">
			<hr class="hr20" >
	     	<div class="layui-row">
	     		<div class="layui-col-xs6">
	      			<span><a href="{% url 'login' %}">已有账号？返回登录</a></span>
	      		</div>
			    <div class="layui-col-xs6" align='right'>
					<span><a href="{% url 'resetpsds' 'resetpsd' %}">忘记密码？密码重置</a></span>
				</div>
			</div>
		</div>
 	</form>
 </div>
{% endblock %}

templates/RBAC/userlist.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
{% csrf_token %}
<div class="x-nav">
	<span class="layui-breadcrumb">
        <a href="">用户管理</a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
      </a>
</div>
<div class="x-body">
	<div class="layui-row ">
		<div class='layui-col-md5'>
	       <form class="layui-form layui-col-md12 x-so">
				<input class="layui-input" placeholder="邮箱地址" name="email" id="id_email">
				<div class="layui-input-inline">
		            <select name="contrller" id ='id_area'>
		              <option value="">所属区域</option>
		              {% for item in area %}
		              	<option value="{{ item.id }}">{{ item.name }}</option>
		              {% endfor %}
		            </select>
		        </div>
		        <div class="layui-input-inline">
			        <select name="contrller" id='id_is_active'>
		              <option value="">账号状态</option>
		              <option value="True">已启用</option>
		              <option value="False">未启用</option>
		            </select>
		        </div>
	       </form>
	     </div>
	     <div class='UserTable'>
	       <button class="layui-btn"  data-type="reload"><i class="layui-icon" >&#xe615;</i></button>
	     </div>
     </div>

	<xblock>
		<div class="UserTable">
			<button class="layui-btn " data-type="disablechoice"><i class="layui-icon layui-icon-close-fill"></i>禁用账号</button>
		    <button class="layui-btn " data-type="enablechoice"><i class="layui-icon layui-icon-auz"></i>启用账号</button>
		    <button class="layui-btn" onclick="x_admin_show('添加用户','{% url 'useradd' %}',600,450)"><i class="layui-icon"></i>添加</button>
		</div>
	</xblock>
	
	<table class="layui-hide" id="user_table" lay-filter="user"></table> 
</div>
<script>
var csrf = $('input[name="csrfmiddlewaretoken"]').val();

layui.use('table', function(){
  var table = layui.table;
  //方法级渲染
  table.render({
    elem: '#user_table'
    ,url: "{% url 'userlist' %}"
    ,method: 'post'
    ,where: {'csrfmiddlewaretoken':csrf}
    ,cols: [[
      {checkbox: true, fixed: true}
      ,{field:'name', title: '姓名', sort: true, fixed: true}
      ,{field:'mail', title: '邮箱地址'}
      ,{field:'date', title: '入驻日期', sort: true}
      ,{field:'area', title: '所属区域',sort: true}
      ,{field:'title', title: '职位信息'}
      ,{field:'role', title: '角色信息'}
      ,{field:'status', title: '账号状态'}
      ,{field:'lastlogin', title: '最后登录'}
    ]]
    ,id: 'testReload'
    ,page: true
    ,limit: 15
    ,text:{
    	none:'暂无相关数据'
    }
  });
  
  var $ = layui.$, active = {
	disablechoice: function(){ //获取选中数据
    	//var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	    var checkStatus = table.checkStatus('testReload')
	    ,data = checkStatus.data
	    ,list=new Array();
    	for(var i=0;i<data.length;i++){
    		list[i] = data[i].mail
    	}
    	layer.confirm('该操作为敏感操作<br>点击确认，禁用用户'+data.mail+'的使用权限，该操作使被禁用用户无法登陆',function(index){
		    $.post("{% url 'userdisactivate' %}",{'user_list':JSON.stringify(list),'action':'stop','csrfmiddlewaretoken': csrf},function(res){
	    		layer.msg(res.error);
	    		setTimeout(function(){
		    		location.replace(location.href);
		    	},2000)
	    	});
    	})
    }
	,enablechoice: function(){ //获取选中数据
	 	//var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	    var checkStatus = table.checkStatus('testReload')
	    ,data = checkStatus.data
	    ,list=new Array();
	 	for(var i=0;i<data.length;i++){
	 		list[i] = data[i].mail
	 	}
	 	layer.confirm('该操作为敏感操作<br>点击确认，启用用户'+data.mail+'的使用权限，该操作使用户可以登录',function(index){
		    $.post("{% url 'userdisactivate' %}",{'user_list':JSON.stringify(list),'action':'start','csrfmiddlewaretoken': csrf},function(res){
	    		layer.msg(res.error);
	    		setTimeout(function(){
		    		location.replace(location.href);
		    	},2000)
	    	});
	 	})
	 }
  ,reload: function(){
      //执行重载
      table.reload('testReload', {
        page: {
          curr: 1 //重新从第 1 页开始
        }
        ,where: {
        	email: $('#id_email').val()
	    	,area: $("#id_area option:selected").val()
	    	,is_active: $("#id_is_active option:selected").val()
        }
      });
    }
  };
  $('.UserTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });
});

</script>
{% endblock %}

templates/RBAC/userregistlist.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
{% csrf_token %}
<div class="x-nav">
	<span class="layui-breadcrumb">
        <a href="">用户注册管理</a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
      </a>
</div>
<div class="x-body">
	<div class="layui-row">
       <div class='layui-col-md8'>
	       <form class="layui-form layui-col-md12 x-so">
				<input class="layui-input" placeholder="邮箱地址" name="email" id="id_email">
				<div class="layui-input-inline">
		            <select name="contrller" id ='id_status'>
		              <option value="">审批状态</option>
		              <option value="0">待审批</option>
		              <option value="1">审批通过</option>
		              <option value="2">审批拒绝</option>
		            </select>
		        </div>
		        <div class="layui-input-inline">
			        <select name="contrller" id='id_is_use'>
		              <option value="">使用状态</option>
		              <option value="True">已使用</option>
		              <option value="False">待使用</option>
		            </select>
		        </div>
		        <div class="layui-input-inline">
			        <select name="contrller" id='id_is_check'>
		              <option value="">审批结果</option>
		              <option value="True">已审批</option>
		              <option value="False">待审批</option>
		            </select>
		        </div>
	       </form>
	     </div>
	     <div class='UserTable'>
	       <button class="layui-btn"  data-type="reload"><i class="layui-icon" >&#xe615;</i></button>
	     </div>
     </div>
	<xblock>
		<div class=" UserTable">
		  <button class="layui-btn " data-type="getCheckData"><i class="layui-icon layui-icon-close-fill"></i>禁用注册</button>
		</div>
	</xblock>	
	<table class="layui-hide" id="user_table" lay-filter="user"></table> 
</div>
<script>
var csrf = $('input[name="csrfmiddlewaretoken"]').val();
layui.use('table', function(){
  var table = layui.table;
	
  //方法级渲染
  table.render({
    elem: '#user_table'
    ,url: "{% url 'userregistlist' %}"
    ,method: 'post'
    ,where: {'csrfmiddlewaretoken':csrf}
    ,cols: [[
      {checkbox: true, fixed: true}
      ,{field:'email', title: '申请邮箱', sort: true, fixed: true}
      ,{field:'is_check', title: '是否审批'}
      ,{field:'is_use', title: '是否使用', sort: true}
      ,{field:'request_type', title: '申请类型'}
      ,{field:'starttime', title: '申请时间'}
      ,{field:'action_user', title: '审批人'}
      ,{field:'updatetime', title: '审批时间'}
      ,{ title: '审批操作',fixed: 'right', align:'center', toolbar: '#barDemo'}
    ]]
    ,id: 'testReload'
    ,page: true
    ,text:{
    	none:'暂无先关数据'
    }
  });
  
  table.on('tool(user)', function(obj){
    var data = obj.data;
    //var csrf = $('input[name="csrfmiddlewaretoken"]').val();
    if(obj.event === 'access'){
    	layer.confirm('该操作为敏感操作<br>点击确认，同意用户'+data.email+'注册为 '+data.request_type,function(index){
    		$.post("{% url 'userregistaction' %}",{'request_id':data.request_id,'action':'access','csrfmiddlewaretoken': csrf},function(res){
        		layer.msg(res.error);
        		setTimeout(function(){
		    		location.replace(location.href);
		    	},2000)
        	});
    	})
    } else if(obj.event === 'deny'){
    	layer.confirm('该操作为敏感操作<br>点击确认，拒绝用户'+data.email+'注册为申请',function(index){
    		$.post("{% url 'userregistaction' %}",{'request_id':data.request_id,'action':'deny','csrfmiddlewaretoken': csrf},function(res){
        		layer.msg(res.error);
        		setTimeout(function(){
		    		location.replace(location.href);
		    	},2000)
        	});
    	})
    }
  });
  var $ = layui.$, active = {
    getCheckData: function(){ //获取选中数据
    	//var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	    var checkStatus = table.checkStatus('testReload')
	    ,data = checkStatus.data
	    ,list=new Array();
    	for(var i=0;i<data.length;i++){
    		list[i] = data[i].request_id
    	}
    	layer.confirm('该操作为敏感操作<br>点击确认，禁用所选用户的注册权限',function(index){
		    $.post("{% url 'userregiststop' %}",{'regist_id_list':JSON.stringify(list),'action':'stop','csrfmiddlewaretoken': csrf},function(res){
	    		layer.msg(res.error);
	    		setTimeout(function(){
		    		location.replace(location.href);
		    	},2000)
	    	});
    	})
    }
	 ,reload: function(){
	     //执行重载
	     table.reload('testReload', {
	       page: {
	         curr: 1 //重新从第 1 页开始
	       }
	       ,where: {
	       	email: $('#id_email').val()
	    	,status: $("#id_status option:selected").val()
	    	,is_use: $("#id_is_use option:selected").val()
	    	,is_check: $("#id_is_check option:selected").val()
	       }
	     });
	   }
  };
  $('.UserTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });
});
</script>

<script type="text/html" id="barDemo">
	{% verbatim %}
	{{# if(d.status=='待审批'){ }}
		<a class="layui-btn layui-btn-xs" lay-event="access">同意</a>
  		<a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="deny">拒绝</a>
	{{# } else { }}
		{{ d.status }}
	{{# } }}
	{% endverbatim %}
</script>
{% endblock %}