RBAC/urls.py
#coding:utf-8
'''
Created on 2018年5月10日

@author: yuguanc
'''

from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('view/', views.login, name='login'),
    path('view/regist/<str:argu>/', views.regist, name='regist'),
    path('view/resetpsd/<str:argu>/', views.resetpasswd, name='resetpsds'),
    path('user/', views.dashboard, name='dashboard'),
    path('user/main/', views.main, name='main'),
    path('user/logout/', views.logout, name='logout'),
    path('user/changepsd/', views.changepsd, name='changepsd'),
    path('user/info/', views.userinfo, name='userinfo'),
    path('user/changeinfo/', views.changeuserinfo, name='changeuserinfo'),
    
    path('manage/user/', views.userlist, name='userview'),
    path('manage/user/list/', views.userlisttable, name='userlist'),
    path('manage/user/add/', views.user_add, name='useradd'),
    path('manage/user/disactivate/', views.user_disactivate, name='userdisactivate'),
    
    path('manage/userrequest/', views.userregistlist, name='userregistview'),
    path('manage/userrequest/list/', views.userregisttable, name='userregistlist'),
    path('manage/userrequest/action/', views.userregistaction, name='userregistaction'),
    path('manage/userrequest/stop/', views.user_request_cancle, name='userregiststop'),
    
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SeMF/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('semf/', admin.site.urls),
    path('',include('RBAC.urls')),
    path('notice/',include('NoticeManage.urls')),
    path('asset/',include('AssetManage.urls')),
    path('vuln/',include('VulnManage.urls')),
    path('chart/',include('ChartManage.urls')),
    path('article/',include('ArticleManage.urls')),
    path('mapped/',include('MappedManage.urls')),
    path('task/',include('TaskManage.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    
#handler404 = views.page_not_found
#handler500 = views.page_error
#handler403 = views.permission_denied

VulnManage/urls.py
#coding:utf-8
'''
Created on 2018年5月14日

@author: yuguanc
'''
from django.urls import path
from .views import views,cnvdviews

urlpatterns = [
    path('user/',views.vulnview,name='vulnview'),
    path('user/list/',views.vulntablelist,name='vulnlist'),
    path('user/listfix/',views.vulnfixlist,name='vulnlistfix'),
    path('user/fix/<str:vuln_id>/',views.vuln_change_status,name='vulnfix'),
    path('user/details/<str:vuln_id>/',views.vulndetails,name='vulndetails'),
    
    
    path('cnvd/',cnvdviews.cnvdvuln_view,name='cnvdvulnview'),
    path('cnvd/list/',cnvdviews.cnvdvulntablelist,name='cnvdvulnlist'),
    path('cnvd/update/<str:cnvdvuln_id>',cnvdviews.cnvdvuln_update,name='cnvdvulnupdate'),
    path('cnvd/details/<str:cnvdvuln_id>',cnvdviews.cnvdvulndetails,name='cnvdvulndetails'),
    path('cnvd/vulnrenew/', cnvdviews.renew, name='cnvdvulnrenew'),
    
    path('manage/create/<str:asset_id>/',views.vulncreate,name='vulncreate'),
    path('manage/update/<str:vuln_id>/',views.vuln_update,name='vulnupdate'),
]

AssetManage/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from RBAC.models import Area,REQUEST_STATUS
# Create your models here.

ASSET_REQUEST_ACTION = (
                        ('工作交接','工作交接'),
                        ('资产认领','资产认领'),
                        )

ASSET_REQUEST_STATUS=(
    ('0','审批中'),
    ('1','审批通过'),
    ('2','审批拒绝'),
    )




class Handover(models.Model):
    dst_email = models.EmailField('目标账号')
    status = models.CharField('申请状态',max_length = 30,choices=ASSET_REQUEST_STATUS,default='0')
    reason = models.TextField('转让说明')
    action_reason = models.TextField('审批说明')
    request_starttime = models.DateField('添加时间',auto_now_add=True)
    request_updatetime = models.DateField('更新时间',auto_now=True)
    
    request_user = models.EmailField('申请账号')
    
    action_user = models.ForeignKey(User,related_name='handover_action_user',on_delete=models.CASCADE,null=True,blank=True)
    def __str__(self):
        return self.id




class AssetType(models.Model):
    name = models.CharField('资产分类',max_length = 30)
    description = models.TextField('资产简介')
    parent = models.ForeignKey('self',verbose_name='父菜单',related_name='assettype_type',null=True,blank=True,on_delete=models.CASCADE)
    
    def __str__(self):
        #显示层级菜单
        return self.name
    
class AssetTypeInfo(models.Model):
    key = models.CharField('属性标识',max_length = 30,unique=True,null=True)
    name = models.CharField('资产属性',max_length = 30)
    type_connect = models.ManyToManyField(AssetType,verbose_name='属性关联',related_name='typeinfo_assettype',blank=True)
    
    def __str__(self):
        return self.name




ASSET_STATUS=(
                ('0','使用中'),
                ('1','闲置中'),
                ('2','已销毁'),
                )
    
class Asset(models.Model):
    asset_id = models.CharField('系统编号',max_length=50,unique=True,null=True)
    asset_out_id = models.CharField('资产编号',max_length=50,null=True,blank=True)
    asset_name = models.CharField('资产名称',max_length = 100)
    asset_key = models.CharField('唯一标记',max_length=50,unique=True)
    asset_description = models.TextField('资产介绍',null=True)
    asset_score = models.IntegerField('重要性估值',default = '0')
    asset_status = models.CharField('资产状态',max_length = 50,choices=ASSET_STATUS,default='0')
    asset_check = models.BooleanField('是否检查',default=False)
    asset_inuse = models.BooleanField('是否认领',default=False)
    asset_starttime = models.DateTimeField('添加时间',auto_now_add=True)
    asset_updatetime = models.DateTimeField('更新时间',auto_now=True)
    
    user_email=models.EmailField('联系人邮箱',null=True,blank=True)
    
    asset_area = models.ForeignKey(Area,related_name='area_for_asset',verbose_name='所属区域',on_delete=models.CASCADE,null=True,blank=True)
    asset_type = models.ForeignKey(AssetType,related_name='type_for_asset',verbose_name='资产类型',on_delete=models.CASCADE,null=True,limit_choices_to={'parent__isnull':False})
    asset_user = models.ManyToManyField(User,related_name='asset_to_user',blank=True)
    
    asset_connect = models.ManyToManyField('self',verbose_name='资产关联',related_name='asset_asset',blank=True)
    
    def __str__(self):
        return self.asset_key
    
    
    
class AssetRequest(models.Model):
    asset_key = models.CharField('申请对象',max_length = 30)
    asset_request_status = models.CharField('状态',max_length = 30,choices=REQUEST_STATUS,default='0')
    request_action = models.CharField('操作类型',max_length = 30,choices=ASSET_REQUEST_ACTION)
    request_reason = models.TextField('申请理由',null=True)
    request_note = models.TextField('审批备注',null=True)
    request_starttime = models.DateTimeField('添加时间',auto_now_add=True)
    request_updatetime = models.DateTimeField('更新时间',auto_now=True)
    
    request_user = models.ForeignKey(User,related_name='assetrequest_for_user',on_delete=models.CASCADE)
    asset_type = models.ForeignKey(AssetType,related_name='type_for_assetrequest',verbose_name='资产类型',on_delete=models.CASCADE,null=True,limit_choices_to={'parent__isnull':False})
    action_user = models.ForeignKey(User,related_name='assetrequestaction_for_user',on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.asset_key



WEB_LANGUAGE=(
    ('C/C++','C/C++'),
    ('C#','C#'),
    ('Ruby','Ruby'),
    ('JAVA','JAVA'),
    ('ASP.NET','ASP.NET'),
    ('JSP','JSP'),
    ('PHP','PHP'),
    ('Perl','Perl'),
    ('Python','Python'),
    ('VB.NET','VB.NET'),
    ('Other','Other'),
    )

WEB_STATUS=(
            ('0','测试系统'),
            ('1','演示系统'),
            ('3','内部使用'),
            ('4','商用系统'),
            )


class OS_Info(models.Model):
    hostname = models.CharField(max_length=50, verbose_name="主机名")
    os = models.CharField("操作系统", max_length=100, blank=True)
    vendor = models.CharField("设备厂商", max_length=50, blank=True)
    cpu_model = models.CharField("CPU型号", max_length=100, blank=True)
    cpu_num = models.CharField("CPU数量", max_length=100, blank=True)
    memory = models.CharField("内存大小", max_length=30, blank=True)
    disk = models.CharField("硬盘大小", max_length=255, blank=True)
    monitor= models.CharField("监控关联", max_length=30, blank=True)
    sn = models.CharField("SN号 码", max_length=60, blank=True)
    cabinet = models.CharField("机柜信息", max_length=50, blank=True)
    
    up_time = models.DateField("上架时间",null=True)
    guarante_time = models.DateField("保修时间",null=True)
    down_time = models.DateField("停用时间",null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.OneToOneField(Asset,related_name='os_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.asset.asset_key




class Internet_Info(models.Model):
    middleware = models.CharField('中间件',max_length=50,blank=True,null=True)
    middleware_version = models.CharField('版本',max_length=50,blank=True,null=True)
    is_out = models.BooleanField('是否发布',default=False)
    out_key = models.CharField('域名',max_length=50,blank=True,null=True)
    web_status = models.CharField('状态说明',max_length = 50,choices=WEB_STATUS,default='测试系统')
    language = models.CharField('开发语言',max_length = 50,choices=WEB_LANGUAGE,null=True)
    language_version = models.CharField('语言版本',max_length = 50,blank=True,null=True)
    web_framwork = models.CharField('开发框架',max_length = 50,blank=True,null=True)
    web_framwork_version = models.CharField('开发框架版本',max_length = 50,blank=True,null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.OneToOneField(Asset,related_name='internet_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.asset.asset_key



class Port_Info(models.Model):
    port = models.CharField('开放端口',max_length=50)
    name = models.CharField('服务名称',max_length=50,null=True)
    product = models.CharField('产品信息',max_length=100,null=True)
    version = models.CharField('应用版本',max_length=50,null=True)
    port_info = models.TextField('端口介绍',null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.ForeignKey(Asset,related_name='port_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.port

class Plugin_Info(models.Model):
    name = models.CharField('组件名称',max_length=50)
    version = models.CharField('应用版本',max_length=50,null=True)
    plugin_info = models.TextField('组件简介',null=True)
    starttime = models.DateTimeField('添加时间',auto_now_add=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.ForeignKey(Asset,related_name='plugin_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
class File(models.Model):
    name = models.CharField('附件名称',max_length=50)
    file = models.FileField('附件内容',upload_to ='assetfiles/%Y/%m/%d/')
    file_info = models.TextField('附件说明',null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.ForeignKey(Asset,related_name='file_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    
class AssetUser(models.Model):
    dst_user_email = models.EmailField('目标账号')
    reason = models.TextField('指定说明')
    asset_list = models.TextField('资产列表')
    request_updatetime = models.DateField('更新时间',auto_now=True)
    
    action_user = models.ForeignKey(User,related_name='assetuser_action_user',on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.dst_user_email   

RBAC/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import django.utils.timezone as timezone

# Create your models here.

class Area(models.Model):
    name = models.CharField('属地信息',max_length = 90,unique=True)
    parent = models.ForeignKey('self',verbose_name='父级属地',related_name='assetarea_area',null=True,blank=True,on_delete=models.CASCADE)
    def __str__(self):
        #显示层级菜单
        title_list = [self.name]
        p = self.parent
        while p:
            title_list.insert(0,p.name)
            p = p.parent
        return '-'.join(title_list)

#设置菜单
class Menu(models.Model):
    title = models.CharField(u'菜单标题',max_length = 25,unique=True)
    icon = models.CharField(u'菜单图标',max_length = 50)
    parent = models.ForeignKey('self',verbose_name=u'父菜单',related_name='menu_menu',null=True,blank=True,on_delete=models.CASCADE)
    
    def __str__(self):
        #显示层级菜单
        title_list = [self.title]
        p = self.parent
        while p:
            title_list.insert(0,p.title)
            p = p.parent
        return '-'.join(title_list)

#设置访问链接
class Permission(models.Model):
    title = models.CharField(u'权限标题',max_length = 50,unique=True)
    is_menu = models.BooleanField('菜单显示',default=False)
    url = models.CharField(max_length=128)
    menu = models.ForeignKey(Menu, null=True,verbose_name=u'权限菜单',related_name='permission_menu',on_delete=models.CASCADE)
    
    def __str__(self):
        return '{menu}--{permission}'.format(menu=self.menu,permission=self.title)
    
#设置角色和权限
class Role(models.Model):
    title = models.CharField(u'角色名称',max_length=25,unique=True)
    permissions = models.ManyToManyField(Permission,verbose_name=u'权限菜单',related_name='role_permission')
    
    def __str__(self):
        return self.title

REQUEST_STATUS=(
    ('0','待审批'),
    ('1','审批通过'),
    ('2','审批拒绝'),
    )

#注册有审批时使用
class UserRequest(models.Model):
    email = models.EmailField('申请邮箱')
    urlarg = models.CharField('注册参数',max_length=50)
    status = models.CharField('审批状态',max_length=50,default='0',choices=REQUEST_STATUS)
    is_check = models.BooleanField('是否审批',default=False)
    is_use = models.BooleanField('是否使用',default=False)
    request_type = models.ForeignKey(Role,verbose_name=u'账号权限',related_name='userrequest_role',on_delete=models.CASCADE)
    starttime = models.DateTimeField('申请时间',auto_now_add=True)
    updatetime = models.DateTimeField('审批时间',auto_now=True)
    
    area =  models.ForeignKey(Area,verbose_name='所属区域',related_name='userrequest_area',null=True,on_delete=models.CASCADE,limit_choices_to={'parent__isnull':True})
    action_user = models.ForeignKey(User,related_name='regist_for_actionuser',on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.email
    
    
#重置密码时使用
class UserResetpsd(models.Model):
    email = models.EmailField('申请邮箱')
    urlarg = models.CharField('重置参数',max_length=50)
    is_check = models.BooleanField('是否使用',default=False)
    updatetime = models.DateField('更新时间',auto_now=True)
    def __str__(self):
        return self.email




#用户附加属性
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    user_num =  models.CharField(u'员工编号',max_length=50,null=True,blank=True)
    title =  models.CharField(u'职位名称',max_length=50)
    
    telephone = models.CharField(u'座机号码',max_length=50,null=True,blank=True)
    mobilephone = models.CharField(u'手机号码',max_length=50)
    description = models.TextField(u'用户简介')
    error_count = models.IntegerField(u'错误登陆',default=0)
    lock_time = models.DateTimeField(u'锁定时间',default = timezone.now)
    
    parent_email = models.EmailField('上级邮箱',null=True,blank=True)
    parent = models.ForeignKey(User,verbose_name='上级汇报',related_name='user_parent',null=True,blank=True,on_delete=models.CASCADE)
    area =  models.ForeignKey(Area,verbose_name='所属区域',related_name='user_area',null=True,on_delete=models.CASCADE,limit_choices_to={'parent__isnull':True})
    
    roles = models.ManyToManyField(Role,verbose_name=u'所属角色',related_name='user_role')
    
    def __str__(self):
        return self.user.username

#同步保存信息  
@receiver(post_save, sender=User) 
def create_user_profile(sender, instance, created, **kwargs):  
    if created:  
        Profile.objects.get_or_create(user=instance)  

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

templates/VulnManage/advancevulnlist.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
{% csrf_token %}
<div class="x-nav">
	<span class="layui-breadcrumb">
        <a href="">漏洞管理</a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
      </a>
</div>
<div class="x-body">
	<div class="layui-row  ">
		<div class='layui-col-md6'>
	       <form class="layui-form layui-col-md12 x-so">
				<input class="layui-input" placeholder="资产关联" name="key" id="id_key">
				<div class="layui-input-inline">
		           <select name="contrller" id ='id_leave'>
		              <option value="">威胁等级</option>
		              <option value="1">低危</option>
		              <option value="2">中危</option>
		              <option value="3">高危</option>
		              <option value="4">紧急</option>
		            </select>
		        </div>
		        <div class="layui-input-inline">
		            <select name="contrller" id ='id_vuln_type'>
		              <option value="">修复状态</option>
		              <option value="0">已忽略</option>
		              <option value="1">已修复</option>
		              <option value="2">待修复</option>
		              <option value="3">漏洞重现</option>
		              <option value="4">复查中</option>
		            </select>
		        </div>
	       </form>
	     </div>
	     <div class='UserTable'>
	       <button class="layui-btn"  data-type="reload"><i class="layui-icon" >&#xe615;</i></button>
	     </div>
     </div>

	<xblock>
		<div class="UserTable">
			<button class="layui-btn " data-type="statuschoice"><i class="layui-icon layui-icon-senior"></i>批量变更</button>
		</div>
	</xblock>
	
	<table class="layui-hide" id="vuln_table" lay-filter="vuln"></table> 
</div>
<script>
var csrf = $('input[name="csrfmiddlewaretoken"]').val();

layui.use('table', function(){
  var table = layui.table;
  //方法级渲染
  table.render({
    elem: '#vuln_table'
    ,url: "{% url 'vulnlist' %}"
    ,method: 'post'
    ,where: {'csrfmiddlewaretoken':csrf}
    ,cols: [[
      {checkbox: true, fixed: true}
      ,{field:'vuln_id', title: '漏洞编号', sort: true, fixed: true}
      ,{field:'vuln_name', title: '漏洞名称'}
      ,{field:'cve_name', title: 'cve编号', sort: true}
      ,{field:'asset', title: '关联资产', event:'Asset'}
      ,{field:'vuln_type', title: '漏洞分类', sort: true}
      ,{field:'leave', title: '威胁等级',sort: true}
      ,{field:'fix_status', title: '修复状态',sort: true}
      ,{field:'update_data', title: '更新时间'}
      ,{ title: '高级选项',fixed: 'right', align:'center', toolbar: '#barDemo'}
    ]]
    ,id: 'vulnsReload'
    ,page: true
    ,limit: 15
    ,text:{
    	none:'暂无相关数据'
    }
  });
  
  table.on('tool(vuln)', function(obj){
    var data = obj.data.asset_id
    ,vuln_id = obj.data.vuln_id
    if(obj.event === 'Asset'){
    	url = "{% url 'assetdetails' '0' %}";
    	url = url.replace(/0/,data);
    	x_admin_show('资产详情',url);
    } else if(obj.event === 'status'){
    	url = "{% url 'vulnfix' 'key' %}";
    	url = url.replace(/key/,vuln_id);
    	x_admin_show('资产详情',url,600,600);
    } else if(obj.event === 'detail'){
    	url = "{% url 'vulndetails' '0' %}";
    	url = url.replace(/0/,vuln_id);
    	x_admin_show('漏洞详情',url,600);
    }
    else if(obj.event === 'edit'){
    	url = "{% url 'vulnupdate' '0' %}";
    	url = url.replace(/0/,vuln_id);
    	x_admin_show('信息变更',url,600);
    }
  });
  
  
  
  var $ = layui.$, active = {
	statuschoice: function(){ //获取选中数据
    	//var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	    var checkStatus = table.checkStatus('vulnsReload')
	    ,data = checkStatus.data
	    ,list=new Array();
    	for(var i=0;i<data.length;i++){
    		list[i] = data[i].vuln_id
    	}
    	layer.confirm('该操作为敏感操作<br>点击确认，选中资产将变更为复查状态',function(index){
		    $.post("{% url 'vulnlistfix' %}",{'vuln_id_list':JSON.stringify(list),'action':'status','csrfmiddlewaretoken': csrf},function(res){
	    		layer.msg(res.error);
	    		setTimeout(function(){
		    		location.replace(location.href);
		    	},2000)
	    	});
    	})
    }
  	,reload: function(){
      //执行重载
      table.reload('vulnsReload', {
        page: {
          curr: 1 //重新从第 1 页开始
        }
        ,where: {
	    	key: $("#id_key").val()
	    	,leave: $("#id_leave option:selected").val()
	    	,fix_status: $("#id_vuln_type option:selected").val()
        }
      });
    }
  };
  $('.UserTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });
});

</script>
<script type="text/html" id="barDemo">
<div class="layui-btn-group">
	{% if user.is_superuser %}
		<a class="layui-btn layui-btn-xs" lay-event="edit"><i class="layui-icon">&#xe642;</i></a>
	{% endif %}
  	<a class="layui-btn layui-btn-xs" lay-event="status"><i class="layui-icon">&#xe674;</i></a>
	<a class="layui-btn layui-btn-xs" lay-event="detail"><i class="layui-icon">&#xe60a;</i></a>
</div>
</script>
{% endblock %}

templates/VulnManage/cnvdvulnlist.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
{% csrf_token %}
<div class="x-nav">
	<span class="layui-breadcrumb">
        <a href="">漏洞库</a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
      </a>
</div>
<div class="x-body">
	<div class="layui-row  ">
		<div class='layui-col-md4'>
	       <form class="layui-form layui-col-md12 x-so">
				<input class="layui-input" placeholder="名称/cve/cnvd" name="name" id="id_name">
				<div class="layui-input-inline">
		           <select name="contrller" id ='id_leave'>
		              <option value="">威胁等级</option>
		              <option value="低">低危</option>
		              <option value="中">中危</option>
		              <option value="高">高危</option>
		            </select>
		        </div>
	       </form>
	     </div>
	     <div class='UserTable'>
	       <button class="layui-btn"  data-type="reload"><i class="layui-icon" >&#xe615;</i></button>
	     </div>
     </div>
     {% if user.is_superuser %}
     <xblock>
		<div class="UserTable">
			<button class="layui-btn" onclick="x_admin_show('漏洞库更新','{% url 'cnvdvulnrenew' %}',600,300)"><i class="layui-icon"></i>漏洞库更新</button>
		</div>
	</xblock>
	{% endif %}
	<table class="layui-hide" id="vuln_table" lay-filter="vuln"></table> 
</div>
<script>
var csrf = $('input[name="csrfmiddlewaretoken"]').val();

layui.use('table', function(){
  var table = layui.table;
  //方法级渲染
  table.render({
    elem: '#vuln_table'
    ,url: "{% url 'cnvdvulnlist' %}"
    ,method: 'post'
    ,where: {'csrfmiddlewaretoken':csrf}
    ,cols: [[
      {field:'cve_id', title: 'cve编号', sort: true, fixed: true}
      ,{field:'cnvd_id', title: 'cnvd编号', event:'vuln'}
      ,{field:'cve_name', title: '漏洞名称', sort: true}
      ,{field:'leave', title: '威胁等级'}
      ,{field:'update_data', title: '更新时间',sort: true}
      ,{ title: '高级选项',fixed: 'right', align:'center', toolbar: '#barDemo'}
    ]]
    ,id: 'vulnsReload'
    ,page: true
    ,limit: 15
    ,text:{
    	none:'暂无相关数据'
    }
  });
  
  table.on('tool(vuln)', function(obj){
    var data = obj.data.id;
    if(obj.event === 'vuln'){
    	url = "{% url 'cnvdvulndetails' '0' %}";
    	url = url.replace(/0/,data);
    	x_admin_show('资产详情',url);
    } else if(obj.event === 'detail'){
    	url = "{% url 'cnvdvulndetails' '0' %}";
    	url = url.replace(/0/,data);
    	window.open(url);
    }
    else if(obj.event === 'edit'){
    	url = "{% url 'cnvdvulnupdate' '0' %}";
    	url = url.replace(/0/,data);
    	x_admin_show('信息变更',url,600);
    }
  });
  
  
  
  var $ = layui.$, active = {
  reload: function(){
      //执行重载
      table.reload('vulnsReload', {
        page: {
          curr: 1 //重新从第 1 页开始
        }
        ,where: {
        	name: $("#id_name").val()
	    	,leave: $("#id_leave option:selected").val()
        }
      });
    }
  };
  $('.UserTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });
});

</script>
<script type="text/html" id="barDemo">
<div class="layui-btn-group">
	{% if user.is_superuser %}
		<a class="layui-btn layui-btn-xs" lay-event="edit"><i class="layui-icon">&#xe642;</i></a>
	{% endif %}
	<a class="layui-btn layui-btn-xs" lay-event="detail"><i class="layui-icon">&#xe60a;</i></a>
</div>
</script>
{% endblock %}