NoticeManage/urls.py
#coding:utf-8
'''
Created on 2018年5月14日

@author: yuguanc
'''
from django.urls import path
from . import views

urlpatterns = [
    path('',views.notice_view,name='noticeview'),
    path('list/',views.notice_table_list,name='noticelist'),
    path('action/',views.notice_action,name='noticeaction'),
    path('readall/',views.notice_readall,name='noticereadall'),
    path('count/',views.notice_count,name='noticecount'),
    path('read/<str:notice_id>/',views.notice_read,name='noticeread'),
]

RBAC/urls.py
#coding:utf-8
'''
Created on 2018年5月10日

@author: yuguanc
'''

from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('view/', views.login, name='login'),
    path('view/regist/<str:argu>/', views.regist, name='regist'),
    path('view/resetpsd/<str:argu>/', views.resetpasswd, name='resetpsds'),
    path('user/', views.dashboard, name='dashboard'),
    path('user/main/', views.main, name='main'),
    path('user/logout/', views.logout, name='logout'),
    path('user/changepsd/', views.changepsd, name='changepsd'),
    path('user/info/', views.userinfo, name='userinfo'),
    path('user/changeinfo/', views.changeuserinfo, name='changeuserinfo'),
    
    path('manage/user/', views.userlist, name='userview'),
    path('manage/user/list/', views.userlisttable, name='userlist'),
    path('manage/user/add/', views.user_add, name='useradd'),
    path('manage/user/disactivate/', views.user_disactivate, name='userdisactivate'),
    
    path('manage/userrequest/', views.userregistlist, name='userregistview'),
    path('manage/userrequest/list/', views.userregisttable, name='userregistlist'),
    path('manage/userrequest/action/', views.userregistaction, name='userregistaction'),
    path('manage/userrequest/stop/', views.user_request_cancle, name='userregiststop'),
    
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SeMF/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('semf/', admin.site.urls),
    path('',include('RBAC.urls')),
    path('notice/',include('NoticeManage.urls')),
    path('asset/',include('AssetManage.urls')),
    path('vuln/',include('VulnManage.urls')),
    path('chart/',include('ChartManage.urls')),
    path('article/',include('ArticleManage.urls')),
    path('mapped/',include('MappedManage.urls')),
    path('task/',include('TaskManage.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    
#handler404 = views.page_not_found
#handler500 = views.page_error
#handler403 = views.permission_denied

NoticeManage/models.py
#coding:utf-8

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
import django.utils.timezone as timezone

# Create your models here.

NOTICE_TYPE = (
                ('notice','安全通告'),
                ('inform','任务通知'),
               )

class Notice(models.Model):
    notice_title = models.CharField('通知标题',max_length = 30)
    notice_body = models.TextField('通知内容')
    notice_status = models.BooleanField('阅读状态',default = False)
    notice_url = models.CharField('父链接',max_length = 50,null=True)
    notice_type = models.CharField('通知类型',max_length = 30,choices=NOTICE_TYPE)
    notice_time = models.DateTimeField('通知时间',default = timezone.now)
    
    notice_user = models.ForeignKey(User,related_name='notice_for_user',verbose_name=u'所属用户',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.notice_title

NoticeManage/views.py
#coding:utf-8

from django.shortcuts import render,get_object_or_404,HttpResponseRedirect
from . import models
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.http import JsonResponse
from SeMFSetting.views import paging
import json
from django.utils.html import escape
# Create your views here.

@login_required
def notice_read(request,notice_id):
    user = request.user
    
    notice = get_object_or_404(models.Notice,notice_user =user ,id =notice_id)
    notice.notice_status = True
    notice.save()
    return HttpResponseRedirect(notice.notice_url)



@login_required
def notice_count(request):
    user = request.user
    notice_count = user.notice_for_user.filter(notice_status = False).count()
    return JsonResponse({'notice_count':notice_count})



@login_required
@csrf_protect
def notice_readall(request):
    user = request.user
    error = '操作成功'
    action = request.POST.get('action')
    if action =='readall':
        notice_list = user.notice_for_user.filter(notice_status = False)
        for notice_get in notice_list:
            notice_get.notice_status = True
            notice_get.save()
    else:
        error = '参数错误'
    return JsonResponse({'error':error})



@login_required
@csrf_protect
def notice_action(request):
    user = request.user
    error = '操作成功'
    notice_id_list = request.POST.get('notice_id_list')
    notice_id_list=json.loads(notice_id_list)
    action = request.POST.get('action')
    #notice_id_list = ast.literal_eval(notice_id_list)
    for notice_id in notice_id_list:
        notice_get = get_object_or_404(models.Notice,notice_user =user ,id =notice_id )
        if action =='delete':
            notice_get.delete()
        elif action =='read':
            notice_get.notice_status = True
            notice_get.save()
        elif action =='unread':
            notice_get.notice_status = False
            notice_get.save()
        else:
            error= '参数错误'
    return JsonResponse({'error':error})
    
    



@login_required
@csrf_protect
def notice_table_list(request):
    user = request.user
    resultdict={}
    
    page = request.POST.get('page')
    rows = request.POST.get('limit')
    notice_type=request.POST.get('notice_type')
    if not notice_type:
        notice_type = ''
    notice_status=request.POST.get('notice_status')
    if not notice_status:
        notice_status = ['True','False']
    else:
        notice_status = [notice_status]
    
    notice_list = models.Notice.objects.filter(notice_user = user,notice_status__in = notice_status,notice_type__icontains=notice_type).order_by('-notice_time')
    total = notice_list.count()
    notice_list = paging(notice_list,rows,page)
    data = []
    for notice in notice_list:
        dic={}
        dic['id'] =escape( notice.id)
        dic['notice_title'] =escape( notice.notice_title)
        dic['notice_body'] =escape( notice.notice_body)
        if notice.notice_status:
            dic['notice_status'] =escape( '已读')
        else:
            dic['notice_status'] =escape( '未读')
        dic['notice_time'] =escape( notice.notice_time)
        data.append(dic)
    resultdict['code']=0
    resultdict['msg']="用户申请列表"
    resultdict['count']=total
    resultdict['data']=data
    return JsonResponse(resultdict)
        


@login_required
def notice_view(request):
    return render(request,'NoticeManage/noticelist.html')



def notice_add(user,data):
    '''           
                这里的 data 为数据字典，内容包括
    {
        'notice_title':'***',
        'notice_body':'***',
        'notice_url':'***',
        'notice_type':'***'
    }
    '''
    notice_title = data.get('notice_title')
    notice_body = data.get('notice_body')
    notice_type = data.get('notice_type')
    notice_url = data.get('notice_url')
    
    notice_body = notice_body
    
    res = models.Notice.objects.get_or_create(
        notice_title=notice_title,
        notice_body=notice_body,
        notice_type=notice_type,
        notice_url=notice_url,
        notice_user=user,
        )
    if res[1]:
        return False
    else:
        res[0].notice_status=False
        res[0].save()
        return True
    

templates/NoticeManage/noticelist.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
{% csrf_token %}
<div class="x-nav">
	<span class="layui-breadcrumb">
        <a href="">用户管理</a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
      </a>
</div>
<div class="x-body">
	<div class="layui-row  ">
		<div class='layui-col-md3'>
	       <form class="layui-form layui-col-md12 x-so">
		        <div class="layui-input-inline">
			        <select name="contrller" id='id_notice_type'>
		              <option value="">消息类型</option>
		              <option value="notice">系统通告</option>
		              <option value="inform">任务通知</option>
		            </select>
		        </div>
		        <div class="layui-input-inline">
			        <select name="contrller" id='id_notice_status'>
		              <option value="">消息状态</option>
		              <option value="True">已读</option>
		              <option value="False">未读</option>
		            </select>
		        </div>
	       </form>
	     </div>
	     <div class='UserTable'>
	       <button class="layui-btn"  data-type="reload"><i class="layui-icon" >&#xe615;</i></button>
	     </div>
     </div>

	<xblock>
		<div class="UserTable">
			<button class="layui-btn " data-type="deletechoice"><i class="layui-icon layui-icon-delete"></i>删除</button>
			<button class="layui-btn " data-type="readchoice"><i class="layui-icon layui-icon-ok-circle"></i>已读</button>
		    <button class="layui-btn " data-type="readall"><i class="layui-icon layui-icon-auz"></i>全部已读</button>
		</div>
	</xblock>
	<table class="layui-hide" id="notice_table" lay-filter="notice"></table> 
	
</div>
<script>
var csrf = $('input[name="csrfmiddlewaretoken"]').val();

layui.use('table', function(){
  var table = layui.table;
  //方法级渲染
  table.render({
    elem: '#notice_table'
    ,url: "{% url 'noticelist' %}"
    ,method: 'post'
    ,where: {'csrfmiddlewaretoken':csrf}
    ,cols: [[
      {checkbox: true, fixed: true}
      ,{field:'notice_title', title: '标题',width:150, fixed: true}
      ,{field:'notice_body', title: '通知内容', event:'read'}
      ,{field:'notice_status', title: '阅读状态',width:100}
      ,{field:'notice_time', title: '通知日期',width:200, sort: true}
    ]]
    ,id: 'testReload'
    ,page: true
    ,limit: 15
  });
  
  table.on('tool(notice)', function(obj){
	    var data = obj.data.id;
	    if(obj.event === 'read'){
	    	url = "{% url 'noticeread' '0' %}";
	    	url = url.replace(/0/,data);
	    	//x_admin_show('详情',url);
	    	var w=($(window).width()*0.9);
	    	var h=($(window).height() - 50);
	    	layer.open({
	            type: 2,
	            area: [w+'px', h +'px'],
	            fix: false, //不固定
	            maxmin: true,
	            shadeClose: true,
	            shade:0.4,
	            title: '详情',
	            content: url,
	            end: function(){
	            	location.replace(location.href);
	            }
	        });
	    }
	  });
  
  var $ = layui.$, active = {
	deletechoice: function(){ //获取选中数据
    	//var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	    var checkStatus = table.checkStatus('testReload')
	    ,data = checkStatus.data
	    ,list=new Array();
    	for(var i=0;i<data.length;i++){
    		list[i] = data[i].id
    	}
    	layer.confirm('该操作为敏感操作<br>点击确认，删除选中消息，删除后将无法恢复',function(index){
		    $.post("{% url 'noticeaction' %}",{'notice_id_list':JSON.stringify(list),'action':'delete','csrfmiddlewaretoken': csrf},function(res){
		    	layer.msg(res.error);
		    	setTimeout(function(){
		    		location.replace(location.href);
		    	},2000)
	    	});
    	})
    }
	,readchoice: function(){ //获取选中数据
	 	//var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	    var checkStatus = table.checkStatus('testReload')
	    ,data = checkStatus.data
	    ,list=new Array();
	 	for(var i=0;i<data.length;i++){
	 		list[i] = data[i].id
	 	}
	 	
	    $.post("{% url 'noticeaction' %}",{'notice_id_list': JSON.stringify(list),'action':'read','csrfmiddlewaretoken': csrf},function(res){
    		layer.msg(res.error);
    		setTimeout(function(){
	    		location.replace(location.href);
	    	},2000)
	 	})
	 }
	,readall: function(){ //获取选中数据
	    $.post("{% url 'noticereadall' %}",{'action':'readall','csrfmiddlewaretoken': csrf},function(res){
	    	layer.msg(res.error);
	    	setTimeout(function(){
	    		location.replace(location.href);
	    	},2000)
    		
	 	})
	 }
  	,reload: function(){
      //执行重载
      table.reload('testReload', {
        page: {
          curr: 1 //重新从第 1 页开始
        }
        ,where: {
	    	notice_status: $("#id_notice_status option:selected").val()
	    	,notice_type: $("#id_notice_type option:selected").val()
        }
      });
    }
  };
  $('.UserTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });
});

</script>
{% endblock %}