RBAC/urls.py
#coding:utf-8
'''
Created on 2018年5月10日

@author: yuguanc
'''

from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('view/', views.login, name='login'),
    path('view/regist/<str:argu>/', views.regist, name='regist'),
    path('view/resetpsd/<str:argu>/', views.resetpasswd, name='resetpsds'),
    path('user/', views.dashboard, name='dashboard'),
    path('user/main/', views.main, name='main'),
    path('user/logout/', views.logout, name='logout'),
    path('user/changepsd/', views.changepsd, name='changepsd'),
    path('user/info/', views.userinfo, name='userinfo'),
    path('user/changeinfo/', views.changeuserinfo, name='changeuserinfo'),
    
    path('manage/user/', views.userlist, name='userview'),
    path('manage/user/list/', views.userlisttable, name='userlist'),
    path('manage/user/add/', views.user_add, name='useradd'),
    path('manage/user/disactivate/', views.user_disactivate, name='userdisactivate'),
    
    path('manage/userrequest/', views.userregistlist, name='userregistview'),
    path('manage/userrequest/list/', views.userregisttable, name='userregistlist'),
    path('manage/userrequest/action/', views.userregistaction, name='userregistaction'),
    path('manage/userrequest/stop/', views.user_request_cancle, name='userregiststop'),
    
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SeMF/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('semf/', admin.site.urls),
    path('',include('RBAC.urls')),
    path('notice/',include('NoticeManage.urls')),
    path('asset/',include('AssetManage.urls')),
    path('vuln/',include('VulnManage.urls')),
    path('chart/',include('ChartManage.urls')),
    path('article/',include('ArticleManage.urls')),
    path('mapped/',include('MappedManage.urls')),
    path('task/',include('TaskManage.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    
#handler404 = views.page_not_found
#handler500 = views.page_error
#handler403 = views.permission_denied

AssetManage/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from RBAC.models import Area,REQUEST_STATUS
# Create your models here.

ASSET_REQUEST_ACTION = (
                        ('工作交接','工作交接'),
                        ('资产认领','资产认领'),
                        )

ASSET_REQUEST_STATUS=(
    ('0','审批中'),
    ('1','审批通过'),
    ('2','审批拒绝'),
    )




class Handover(models.Model):
    dst_email = models.EmailField('目标账号')
    status = models.CharField('申请状态',max_length = 30,choices=ASSET_REQUEST_STATUS,default='0')
    reason = models.TextField('转让说明')
    action_reason = models.TextField('审批说明')
    request_starttime = models.DateField('添加时间',auto_now_add=True)
    request_updatetime = models.DateField('更新时间',auto_now=True)
    
    request_user = models.EmailField('申请账号')
    
    action_user = models.ForeignKey(User,related_name='handover_action_user',on_delete=models.CASCADE,null=True,blank=True)
    def __str__(self):
        return self.id




class AssetType(models.Model):
    name = models.CharField('资产分类',max_length = 30)
    description = models.TextField('资产简介')
    parent = models.ForeignKey('self',verbose_name='父菜单',related_name='assettype_type',null=True,blank=True,on_delete=models.CASCADE)
    
    def __str__(self):
        #显示层级菜单
        return self.name
    
class AssetTypeInfo(models.Model):
    key = models.CharField('属性标识',max_length = 30,unique=True,null=True)
    name = models.CharField('资产属性',max_length = 30)
    type_connect = models.ManyToManyField(AssetType,verbose_name='属性关联',related_name='typeinfo_assettype',blank=True)
    
    def __str__(self):
        return self.name




ASSET_STATUS=(
                ('0','使用中'),
                ('1','闲置中'),
                ('2','已销毁'),
                )
    
class Asset(models.Model):
    asset_id = models.CharField('系统编号',max_length=50,unique=True,null=True)
    asset_out_id = models.CharField('资产编号',max_length=50,null=True,blank=True)
    asset_name = models.CharField('资产名称',max_length = 100)
    asset_key = models.CharField('唯一标记',max_length=50,unique=True)
    asset_description = models.TextField('资产介绍',null=True)
    asset_score = models.IntegerField('重要性估值',default = '0')
    asset_status = models.CharField('资产状态',max_length = 50,choices=ASSET_STATUS,default='0')
    asset_check = models.BooleanField('是否检查',default=False)
    asset_inuse = models.BooleanField('是否认领',default=False)
    asset_starttime = models.DateTimeField('添加时间',auto_now_add=True)
    asset_updatetime = models.DateTimeField('更新时间',auto_now=True)
    
    user_email=models.EmailField('联系人邮箱',null=True,blank=True)
    
    asset_area = models.ForeignKey(Area,related_name='area_for_asset',verbose_name='所属区域',on_delete=models.CASCADE,null=True,blank=True)
    asset_type = models.ForeignKey(AssetType,related_name='type_for_asset',verbose_name='资产类型',on_delete=models.CASCADE,null=True,limit_choices_to={'parent__isnull':False})
    asset_user = models.ManyToManyField(User,related_name='asset_to_user',blank=True)
    
    asset_connect = models.ManyToManyField('self',verbose_name='资产关联',related_name='asset_asset',blank=True)
    
    def __str__(self):
        return self.asset_key
    
    
    
class AssetRequest(models.Model):
    asset_key = models.CharField('申请对象',max_length = 30)
    asset_request_status = models.CharField('状态',max_length = 30,choices=REQUEST_STATUS,default='0')
    request_action = models.CharField('操作类型',max_length = 30,choices=ASSET_REQUEST_ACTION)
    request_reason = models.TextField('申请理由',null=True)
    request_note = models.TextField('审批备注',null=True)
    request_starttime = models.DateTimeField('添加时间',auto_now_add=True)
    request_updatetime = models.DateTimeField('更新时间',auto_now=True)
    
    request_user = models.ForeignKey(User,related_name='assetrequest_for_user',on_delete=models.CASCADE)
    asset_type = models.ForeignKey(AssetType,related_name='type_for_assetrequest',verbose_name='资产类型',on_delete=models.CASCADE,null=True,limit_choices_to={'parent__isnull':False})
    action_user = models.ForeignKey(User,related_name='assetrequestaction_for_user',on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.asset_key



WEB_LANGUAGE=(
    ('C/C++','C/C++'),
    ('C#','C#'),
    ('Ruby','Ruby'),
    ('JAVA','JAVA'),
    ('ASP.NET','ASP.NET'),
    ('JSP','JSP'),
    ('PHP','PHP'),
    ('Perl','Perl'),
    ('Python','Python'),
    ('VB.NET','VB.NET'),
    ('Other','Other'),
    )

WEB_STATUS=(
            ('0','测试系统'),
            ('1','演示系统'),
            ('3','内部使用'),
            ('4','商用系统'),
            )


class OS_Info(models.Model):
    hostname = models.CharField(max_length=50, verbose_name="主机名")
    os = models.CharField("操作系统", max_length=100, blank=True)
    vendor = models.CharField("设备厂商", max_length=50, blank=True)
    cpu_model = models.CharField("CPU型号", max_length=100, blank=True)
    cpu_num = models.CharField("CPU数量", max_length=100, blank=True)
    memory = models.CharField("内存大小", max_length=30, blank=True)
    disk = models.CharField("硬盘大小", max_length=255, blank=True)
    monitor= models.CharField("监控关联", max_length=30, blank=True)
    sn = models.CharField("SN号 码", max_length=60, blank=True)
    cabinet = models.CharField("机柜信息", max_length=50, blank=True)
    
    up_time = models.DateField("上架时间",null=True)
    guarante_time = models.DateField("保修时间",null=True)
    down_time = models.DateField("停用时间",null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.OneToOneField(Asset,related_name='os_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.asset.asset_key




class Internet_Info(models.Model):
    middleware = models.CharField('中间件',max_length=50,blank=True,null=True)
    middleware_version = models.CharField('版本',max_length=50,blank=True,null=True)
    is_out = models.BooleanField('是否发布',default=False)
    out_key = models.CharField('域名',max_length=50,blank=True,null=True)
    web_status = models.CharField('状态说明',max_length = 50,choices=WEB_STATUS,default='测试系统')
    language = models.CharField('开发语言',max_length = 50,choices=WEB_LANGUAGE,null=True)
    language_version = models.CharField('语言版本',max_length = 50,blank=True,null=True)
    web_framwork = models.CharField('开发框架',max_length = 50,blank=True,null=True)
    web_framwork_version = models.CharField('开发框架版本',max_length = 50,blank=True,null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.OneToOneField(Asset,related_name='internet_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.asset.asset_key



class Port_Info(models.Model):
    port = models.CharField('开放端口',max_length=50)
    name = models.CharField('服务名称',max_length=50,null=True)
    product = models.CharField('产品信息',max_length=100,null=True)
    version = models.CharField('应用版本',max_length=50,null=True)
    port_info = models.TextField('端口介绍',null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.ForeignKey(Asset,related_name='port_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.port

class Plugin_Info(models.Model):
    name = models.CharField('组件名称',max_length=50)
    version = models.CharField('应用版本',max_length=50,null=True)
    plugin_info = models.TextField('组件简介',null=True)
    starttime = models.DateTimeField('添加时间',auto_now_add=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.ForeignKey(Asset,related_name='plugin_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
class File(models.Model):
    name = models.CharField('附件名称',max_length=50)
    file = models.FileField('附件内容',upload_to ='assetfiles/%Y/%m/%d/')
    file_info = models.TextField('附件说明',null=True)
    updatetime = models.DateField('更新时间',auto_now=True)
    
    asset = models.ForeignKey(Asset,related_name='file_for_asset',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    
class AssetUser(models.Model):
    dst_user_email = models.EmailField('目标账号')
    reason = models.TextField('指定说明')
    asset_list = models.TextField('资产列表')
    request_updatetime = models.DateField('更新时间',auto_now=True)
    
    action_user = models.ForeignKey(User,related_name='assetuser_action_user',on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.dst_user_email   

templates/Dashboard.html
{% load staticfiles %}
{% load custom_tag %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>SeMF安全管控平台</title>
		<meta name="renderer" content="webkit|ie-comp|ie-stand">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
	    <meta http-equiv="Cache-Control" content="no-siteapp" />
	    
	    
		<link href="{% static '/css/font.css' %}" rel="stylesheet">
		<link href="{% static 'css/xadmin.css' %}" rel="stylesheet">
		
		
	
	    <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script> <!-- jQuery Library -->
	    <script src="{% static 'lib/layui/layui.js' %}" charset="utf-8"></script>
	    <script src="{% static 'js/xadmin.js' %}"></script>
	    
	    <script>
	    function noticecount(){
	    	$.get("{% url 'noticecount' %}",function(res){
	    		if(res.notice_count!=0){
	    			$("#noticecount").append("<span class='layui-badge'>"+ res.notice_count +"</span>")
	    		}
		 	})
	    }
	    $(document).ready(function(){    
			noticecount();
			setInterval(function(){
				noticecount();
	    	},60000)
	    	$("#noticecount").click(function(){
    		  $("#noticecount span ").remove();
    		});
		});
	    </script>
	    
	</head>
	
	<body>
		<!-- 顶部开始 -->
	    <div class="container">
	        <div class="logo" align='center'><a href="#">SeMF安全管控平台</a></div>
	        <div class="left_open">
	            <i title="展开左侧栏" class="iconfont">&#xe699;</i>
	        </div>
	        <ul class="layui-nav left" lay-filter="">
	        	<li class="layui-nav-item">
	        		<a _href="{% url 'noticeview' %}" class='tab_add' id='noticecount'><i class="layui-icon layui-icon-notice"></i></a>
	        	</li>
	        </ul>
	        
            <ul class="layui-nav right" lay-filter="">
		      <li class="layui-nav-item">
		        <a href="javascript:;">
		          <img src="http://t.cn/RCzsdCq" class="layui-nav-img">
		          {{ user }}
		        </a>
		        <dl class="layui-nav-child">
		          <dd><a onclick="x_admin_show('基本信息','{% url 'userinfo'%}',600,700)">基本资料</a></dd>
		          <dd><a onclick="x_admin_show('资料变更','{% url 'changeuserinfo'%}',600,750)">资料变更</a></dd>
		          {% if not user.is_superuser %}
		          	<dd><a onclick="x_admin_show('资产交接','{% url 'assethandover'%}',600,500)">资产交接</a></dd>
		          {% endif %}
		          <dd><a onclick="x_admin_show('更改密码','{% url 'changepsd'%}',600,500)">更改密码</a></dd>
		          <dd><a href="{%  url  'logout' %}">退出登录</a></dd>
		        </dl>
		      </li>
		    </ul>
	    </div>
	    <!-- 顶部结束 -->
	    <!-- 中部开始 -->
	    <!-- 左侧菜单开始 -->
	    <div class="left-nav">
	    	<div id="side-nav">
	    		<ul id="nav">
	    		{% rbac_menu request %}
		        </ul>
	    	</div>
	    </div>
	    <!-- 左侧菜单结束 -->
	    <!-- 右侧主体开始 -->
	    <div class="page-content">
	        <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
	          <ul class="layui-tab-title">
	            <li class="home"><i class="layui-icon">&#xe68e;</i>我的桌面</li>
	          </ul>
	          <div class="layui-tab-content">
	            <div class="layui-tab-item layui-show">
	                <iframe src="{% url 'main' %}" frameborder="0" scrolling="yes" class="x-iframe"></iframe>
	            </div>
	          </div>
	        </div>
	    </div>
	    <div class="page-content-bg"></div>
	    <!-- 右侧主体结束 -->
	    <!-- 中部结束 -->
	    <!-- 底部开始 -->
	    <div class="footer">
	        <div class="copyright" align='center'>Copyright ©2018 SeMF All Rights Reserved </div>
	    </div>
	    <!-- 底部结束 -->
	</body>
</html>

templates/error.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
	<div align='center'>
		<i class='layui-icon layui-icon-website' style="font-size: 500px;"></i><br>
		<h3><strong>警告！</strong>{{ error }} <a href="javascript:history.back(-1)">点我返回</a></h3>
	</div>
{% endblock %}

templates/formedit.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
	<div class="x-body layui-anim layui-anim-up">
		<form class="layui-form" method='post' action="{% url post_url %}" enctype="multipart/form-data">
			<div class="layui-form-item">
				{% csrf_token %}
				{{ form.as_table }}
			</div>
			<div class="layui-row">
				<div class="layui-col-xs6" >
			    	<button type="reset" class="layui-btn layui-btn-radius" >重置表单</button>
			  	</div>
			  	<div class="layui-col-xs6" align='right'>
			    	<button type="submit" class="layui-btn layui-btn-radius" lay-submit lay-filter="form_post" >立即提交</button>
			  	</div>
			 </div>
		</form>
	</div>

<script>
layui.use(['laydate'], function(){
	var laydate = layui.laydate;
	laydate.render({
	    elem: '#id_start_time'
	  });
	laydate.render({
	    elem: '#id_end_time'
	  });
});
layui.use('layedit', function(){
	var layedit = layui.layedit;
	
	layedit.set({
		uploadImage:{
			url:"{% url  'imgupload' %}"
			,type:'post'
		}
	});
	index = layedit.build('id_article_body',{
		height: 300
	}); //建立编辑器
	layui.use('form', function(){
	  var form = layui.form;
	  form.on('submit(form_post)', function(data){
		  layedit.sync(index);
	  });
	});
});

	
</script>
{% endblock %}

templates/formupdate.html
{% extends "index.html" %} 
<meta charset="UTF-8">

{% block index %}
	<div class="x-body layui-anim layui-anim-up">
		<form class="layui-form" method='post' action="{% url post_url argu %}" enctype="multipart/form-data">
			<div class="layui-form-item">
				{% csrf_token %}
				{{ form.as_table }}
			</div>
			<div class="layui-row">
				<div class="layui-col-xs6" >
			    	<button type="reset" class="layui-btn layui-btn-radius" >重置表单</button>
			  	</div>
			  	<div class="layui-col-xs6" align='right'>
			    	<button type="submit" class="layui-btn layui-btn-radius" lay-submit lay-filter="form_post" >立即提交</button>
			  	</div>
			 </div>
		</form>
	</div>
<script>
layui.use(['laydate'], function(){
	var laydate = layui.laydate;
	laydate.render({
	    elem: '#id_up_time'
	  });
	laydate.render({
	    elem: '#id_guarante_time'
	  });
	laydate.render({
	    elem: '#id_down_time'
	  });
});
layui.use('layedit', function(){
	var layedit = layui.layedit;
	
	layedit.set({
		uploadImage:{
			url:"{% url  'imgupload' %}"
			,type:'post'
		}
	});
	index = layedit.build('id_article_body',{
		height: 300
	}); //建立编辑器
	layui.use('form', function(){
	  var form = layui.form;
	  form.on('submit(form_post)', function(data){
		  layedit.sync(index);
	  });
	});
});
</script>
{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>SeMF安全管控平台</title>
		<meta name="renderer" content="webkit|ie-comp|ie-stand">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
	    <meta http-equiv="Cache-Control" content="no-siteapp" />
	    
	    
		<link href="{% static 'css/font.css' %}" rel="stylesheet">
		<link href="{% static 'css/xadmin.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		
	
	    <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script> <!-- jQuery Library -->
	    <script src="{% static 'lib/layui/layui.js' %}" charset="utf-8"></script>
	    <script src="{% static 'js/xadmin.js' %}"></script>
	    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	</head>
	
	<body>
		{% if error %}
			<div class="alert alert-warning alert-dismissible" role="alert">
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  <strong>温馨提示!</strong> {{ error }}
			</div>
		{% endif %}
		{% block index %}
		
		{% endblock %}
		
		
	</body>
</html>